version: "3.8"
services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: order/postgres
    container_name: "db_postgres"
    hostname: db
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d platform_order" ]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 20

  order-help:
    build:
      context: ../
      dockerfile: Dockerfile
    image: order/help
    container_name: "order-help"
    hostname: order-help
    environment:
      - DB_HOSTNAME=db
    ports:
      - "127.0.0.1:892:8092"
    depends_on:
      db:
        condition: service_healthy


